# Generated by Django 3.2.5 on 2021-08-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
